name: 'CI'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup node 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: Setup PHP 7.4 with composer v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer:v2

      - name: Install dependencies
        run: |
          npm ci
          composer i

      - name: Run linters
        run: npm run lint

      - name: Perform build
        run: npm run build
