name: 'Release'

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup node 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: Setup PHP 7.4 with composer v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer:v2

      - name: Install dependencies
        run: |
          npm ci
          composer i

      - name: Perform build
        run: npm run build

      - name: Remove build dependencies
        run: |
          rm -Rf vendor/ node_modules/
          npm ci --production
          composer i --no-dev

      - name: Collect release files
        run: zip -r release.zip . -x ".git/*" -x ".devcontainer/*" -x ".github/*" -x ".vscode/*"

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: release.zip
          generate_release_notes: true
